name: Windows-CI
on:
  push:
    branches:
    - master
    - release*
    - feature*
    paths:
    - "*"
    - "!.vsts-ci/misc-analysis.yml"
    - "!.github/ISSUE_TEMPLATE/*"
    - "!.github/workflows/*"
    - "!.dependabot/config.yml"
    - "!test/perf/*"
    - "!.pipelines/*"
  pull_request:
    branches:
    - master
    - release*
    - feature*
    paths:
    - ".vsts-ci/templates/*"
    - ".vsts-ci/windows.yml"
    - "*.props"
    - build.psm1
    - src/*
    - test/*
    - tools/buildCommon/*
    - tools/ci.psm1
    - tools/WindowsCI.psm1
    - "!test/common/markdown/*"
    - "!test/perf/*"
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  GIT_CONFIG_PARAMETERS: "'core.autocrlf=false'"
  NugetSecurityAnalysisWarningLevel: none
  POWERSHELL_TELEMETRY_OPTOUT: 1
  __SuppressAnsiEscapeSequences: 1
  nugetMultiFeedWarnLevel: none
jobs:
  vsts_ci_templates_ci_build:
    name: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_ci_build.yml"
  vsts_ci_templates_windows_test:
    name: vsts_ci_templates_windows_test
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_windows_test.yml"
    with:
      purpose: UnelevatedPesterTests
      tagSet: CI
  vsts_ci_templates_windows_test_2:
    name: vsts_ci_templates_windows_test_2
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_windows_test.yml"
    with:
      purpose: ElevatedPesterTests
      tagSet: CI
  vsts_ci_templates_windows_test_3:
    name: vsts_ci_templates_windows_test_3
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_windows_test.yml"
    with:
      purpose: UnelevatedPesterTests
      tagSet: Others
  vsts_ci_templates_windows_test_4:
    name: vsts_ci_templates_windows_test_4
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_windows_test.yml"
    with:
      purpose: ElevatedPesterTests
      tagSet: Others
  vsts_ci_templates_verify_xunit:
    name: vsts_ci_templates_verify_xunit
    needs: vsts_ci_templates_ci_build
    uses: "./.github/workflows/vsts_ci_templates_verify_xunit.yml"
